### ISSUE TITLE
False negatives from title attribute check

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#109]
@EmmaJP says this scenario shouldn't exist:

https://github.com/cucumber-ltd/bbc-a11y/blob/master/features/check_standards/11_title_attributes.feature#L37

**Comment by EmmaJP** [comment]
It's not an error ... but it's definitely not good practice: both of those because the title text will not be seen or heard by most users.  Perhaps this is a time to consider warnings (though others may consider this to be dilution).

```
Scenario: Non-input tag with title attribute
    Given a page with the body:
      """
      <a href="close" title="Close Button">
        <img src="close.png" />
      </a>
      """
    When I validate the "title attributes only on inputs" standard
    Then it **warns** with the message:
      """
      Non-input element has title attribute: /html/body/a
      """
```

The MAG navigation error, that bbc-a11y found, is a similar situation to the example at line 37 in the feature file.  It isn't preventing accessibility and it isn't giving any information that is not available by other means.  It is duplicating the text within the link, though this would not error either because that text is hidden.

We've looked at this feature file before.  I still feel that the scenarios should match the guideline rather than the recommendations in the rationale (which are already covered by the "form labels" feature file).

> `title` attributes **must not** be used for critical information

This is rather subjective and probably needs a manual test.  Although there could maybe be a scenario to pick up a title attribute on an element with no text content and give a warning (though input elements may need to be excluded).

> and **must not** repeat content that is already visible and associated with the same control or content.

It should be possible to automate this. For example:

```
Scenario: Title attribute duplicates content
    Given a page with the body:
      """
      <a href="back" title="Back to Home">
        <img src="back.png" /> Back to Home
      </a>
      """
    When I validate the "title attributes only on inputs" standard
    Then it fails with the message:
      """
      Title attribute duplicates content: /html/body/a
      """
```
