### ISSUE TITLE
Suggest fixes

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#146]
Can bbc-a11y suggest fixes instead of just complaining about problems?

**Comment by freeballoon** [comment]
Ideally wire this into the guidelines, so that when the guidelines are updated, so are the suggested fixes.

**Comment by greenc05** [comment]
That would be awesome @joshski

**Comment by EmmaJP** [comment]
Yes, absolutely. The message could provide a quick concept and a link to a guideline, as Steve suggested.

**Comment by JamieKnightBBC** [comment]
Hello,

I think providing feedback is a good idea, but the MAG or HTML "Guide"* is the wrong place to send people.

The MAG's focus is holding requirements, the example code is just that, examples. It should not be treated as production code and i wouldn't be comfortable encouraging people to copy and past from the MAG.

The HTML Guide (due to replace the current standard shortly) is likewise high level best practices recommendations and also probably not a great thing to encourage people to copy and past from. 

Both of those documents are "What" and "How", but for this situation we need more of a guide to debugging etc. Its different enough that the MAG or the HTML Guide is a poor fit.

I'd suggest we have a separate document(s) as part of the github files (perhaps a wiki page, perhaps a new directory in the tree) and have a "debugging guide" for each error in there and then link to that.

That would keep all of the a11y self contained and easy to update / develop over time and would keep the focus of the MAG and other guides to just the "what" and "how".

Hope that helps,

Jamie + Lion

**Comment by EmmaJP** [comment]
I totally agree that the suggestions for what to change will need to be in bbc-a11y. A "debugging guide" file may be a good place to collate them. However, I think it will still be helpful to link to the guidelines for further understanding.
So I guess not exactly what Steve suggested.

**Comment by joshski** [comment]
Thanks @JamieKnightBBC, for now I've linked to the guidelines when things fail, but feel free to open an issue or submit a PR when there is a better place to link to
