### ISSUE TITLE
Exclude or ignore these errors

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#52]
URLS: http://news.bbc.co.uk, http://www.bbc.co.uk/news/politics, http://bbc.co.uk/news/uk
These errors are all from ORB

```
  - Field has no label or title attribute: /html/body/div/header/div/div[1]/div[3]/form/div/input[1]
  - Field has no label or title attribute: /html/body/div/header/div/div[1]/div[3]/form/div/input[3]
  - Field has no label or title attribute: /html/body/div/header/div/div[1]/div[3]/form/div/input[4]
  - Form has no submit button: /html/body/div/header/div/div[1]/div[3]/form
```

URLS: http://news.bbc.co.uk, http://www.bbc.co.uk/news/politics, http://bbc.co.uk/news/uk
This is a 1px x 1px graphic either from stats tracking or from advertising

```
  - Image has no alt attribute (src="http://b.scorecardresearch.com/p?c1=2&c2=17986528&cv=2.0&cj=1")
```

URLS: http://bbc.co.uk/mundo, http://bbc.co.uk/cymrufyw
These errors are all from ORB

```
  - Field has no label or title attribute: /html/body/div/header/div/div[1]/div[3]/form/div/input[1]
  - Field has no label or title attribute: /html/body/div/header/div/div[1]/div[3]/form/div/input[2]
  - Field has no label or title attribute: /html/body/div/header/div/div[1]/div[3]/form/div/input[4]
  - Field has no label or title attribute: /html/body/div/header/div/div[1]/div[3]/form/div/input[5]
  - Form has no submit button: /html/body/div/header/div/div[1]/div[3]/form
```

**Comment by greenc05** [comment]
@EmmaJP we still get these ORB errors, I believe you said that the test needed tweaking as they aren't actually errors, have you done that?

**Comment by joshski** [comment]
For the 1px gif issue, We haven't released a version that ignores invisible elements yet. Are you using the Ruby gem, or github master?

The others look like they are about ignoring regions of the page (issue #52), we haven't implemented that yet.

**Comment by joshski** [comment]
Ha sorry this is issue 52! I need to sleep ;)

**Comment by eemmzz** [comment]
Just thought I'd add a +1 comment asking for this also seeming as it has been a while since this issue was raised. We still get the following error from orb:

`Form has no submit button: /html/body/div/header/div/div[1]/div[3]/form`

I haven't been able to successfully ignore this with `skip_standard` (and I would only like to skip the standard for the above mentioned xpath so that our own forms are validated).

**Comment by JamieKnightBBC** [comment]
+1 to this.

**Comment by EmmaJP** [comment]
Perhaps an approach may be to specify that the results do not include errors that concern a specific area of the page (so ORB issues can be ignored) ... and conversely to only include errors that concern a specific area of the page (so focused testing can be done by the ORB team or content teams).

Both of these are about helping the user to filter out noise in the results, rather than not running the tests on the complete page.

For example, an error could be caused by something in the area of interest clashing/duplicating something in the area not of interest. To pick this up tests would need to run against the whole page. The error would show in the results because it involves something in the area of interest.

Does that make sense?
