### ISSUE TITLE
I'd like to move the config file

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#71]
I'd like to be able to move the config file 'a11y.rb' into the directory with our other Ruby files e.g. /ruby/a11y.rb

**Comment by joshski** [comment]
Thanks @greenc05

We can't guess where you might decide to put your ruby files, and we wouldn't like to search through all directories to find your a11y.rb configuration file, because this could take a long time if you have lots of files in your project.

So the way I see it, there are two options:

* you change directory into your ruby subdirectory before running `a11y` (this should work already):
```
cd ruby
a11y
```
* we make a way of running the tool, but specifying an alternative location of the configuration file, e.g:
```
a11y ./ruby/a11y.rb
```
Obviously in the latter case, you have a more complicated command to remember.

What do you think?

**Comment by staylos92** [comment]
Hi @joshski , my preferred option here would be the 2nd one that you suggested above (being able to specify an alternative location for the config file). This would not only allow us to move the config file to a place of our choosing but would also allow us to easily maintain multiple config files should we wish to split tests out into multiple jobs when running on our CI servers. 

The downside of having to remember a longer command isn't really an issue for us as generally we will only be running the tool on CI and also for other tools we use we generally would specify any config files in a similar manner to what is being suggested above.

Cheers,
Simon
