### ISSUE TITLE
I would like a way to skip a standard for a list of urls

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#92]

**Comment by JamieKnightBBC** [comment]
+1 to this. ORB triggers failures which are causing tests to fall with code outside of my control. Until ORB fix the errors i would like to mute them to get a more accurate view of the test results.

**Comment by joshski** [comment]
Thanks @greenc05 / @JamieKnightBBC 

Did you see this feature? https://github.com/bbc/bbc-a11y/blob/master/features/cli/skipping_standards.feature

Is that what you had in mind? Or perhaps it needs documenting elsewhere?

**Comment by joshski** [comment]
I think it's possible to skip a standard for a URL, and, since the configuration file is in Ruby, it's trivial to skip a check for multiple URLs. I believe the ORB stuff mentioned by @JamieKnightBBC is more about skipping checks for a particular area of the page, which is raised in other issues like https://github.com/bbc/bbc-a11y/issues/52

So I'm closing this. Please reopen if I have missed the point.
